<?PHP

return [

    1 => 'Login',
    2 => 'Sign In',
    3 => 'There was a problem.',
    4 => 'Keep me signed in',
    5 => 'Reset Password',
    6 => 'Sign up',
    7 => 'New to our website?',
    8 => 'Already have an account?',

    9 => 'Analytics',
    10 => 'Live Feed',
    11 => 'Heatmaps',
    12 => 'Technology',
    13 => 'Uptime',
    14 => 'Visitor Search',
    15 => 'A/B Testing',
    16 => 'Site KPIs',
    17 => 'Settings',
    18 => 'General',
    19 => 'Dashboard',
    20 => 'My Sites',
    21 => 'API Docs',
    22 => 'Adverts',

    23 => 'Upgrade',
    24 => 'Help',
    25 => 'Logout',
    26 => 'Add Site',

    27 => 'Name',
    28 => 'Users Online',
    29 => 'Visits today',
    30 => 'Hits today',
    31 => 'Status',
    32 => 'Your Sites',

    33 => 'Affordable pricing. No long term contract. No per-user fees.',
    34 => 'Upgrade your account now.',
    35 => 'Your current plan',
    36 => 'Select Plan',
    37 => 'We proccess your payment with Braintree.',
    38 => 'Payment',
    39 => 'You already have a subscription',
    40 => 'By choosing a new package, we will cancel your previous subscription',
    41 => 'As there is no cost for this package, click the button below to process your account into this package instantly.',

    42 => 'Apply',
    43 => 'Export',
    44 => 'Download PDF',
    45 => 'Download CSV',

    46 => 'Total visits',
    47 => 'Pageviews',
    48 => 'Bounce Rate',
    49 => 'Content',
    50 => 'Page',
    51 => 'Actions',
    52 => 'Visits',
    53 => 'Average Time',

    54 => 'Top Browsers',
    55 => 'Total',
    56 => 'Top Devices',
    57 => 'Top Locations',

    58 => 'LIVE',
    59 => 'Pageviews',
    60 => 'Date',
    61 => 'Location',
    62 => 'Current Page',
    63 => 'Live Content',
    64 => 'Live Browsers',
    65 => 'Browsers',
    66 => 'Live Devices',
    67 => 'Devices',
    68 => 'Live Locations',
    69 => 'Locations',

    70 => 'View',
    71 => 'Kisslytics A/B',
    72 => 'How to setup A/B Testing on your site?',
    73 => 'A/B tests are statistical experiments that help you decide whether a change is actually making a significant impact on your website.',
    74 => 'To run an A/B test on your site, you need to make sure you are doing these 3 things:',
    75 => 'Each visitor is randomly assigned to a variation, either A or B.',
    76 => 'Make sure that the visitor always sees either only A or only B. Otherwise, your results are tainted if someone ends up seeing more than one variation.',
    77 => 'Report on what the users do next - <strong>this is where Kisslytics come in!</strong>',
    78 => 'When a visitor lands on a page that is part of your A/B testing, you\'ll need to add this code to your page. The only bit you need to change is where it says <strong>test A</strong>. Change it to what you want the name of the test to be! Please make sure it is after your tracking code.',
    79 => 'pages',
    80 => 'sessions',
    81 => 'Delete this Test',
    82 => 'Delete',

    83 => 'AB Test not added.',
    84 => 'You are only allowed',
    85 => 'AB Test added',
    86 => 'Add new AB Test',
    87 => 'Create AB Test',

    88 => 'Are you sure?',
    89 => 'You will not be able to recover this AB Test!',
    90 => 'Yes, delete it!',
    91 => 'No, cancel plx!',
    92 => 'Your AB Test is safe :)',

    93 => 'Add a New Site',
    94 => 'Add a new Site and Start<br/> to collect Analytics inmediately!',
    95 => 'Timezone',
    96 => 'Create this site',

    97 => 'Delete this Heatmap',
    98 => 'Heatmaps should only be created for public accessible pages.',
    99 => 'We cannot display screenshots for any pages that require a username/password.',
    100 => 'Heatmap not added.',
    101 => 'Heatmap added.',
    102 => 'Add new URL',
    103 => 'Create Heatmap Page',
    104 => 'You will not be able to recover this heatmap!',
    105 => 'Your heatmap is safe :)',
    106 => 'My Heatmaps',
    107 => 'Create KPI Report',
    108 => 'Date period',

    109 => 'Settings',
    110 => 'Embed Tracking Code',
    111 => 'API TOKEN',
    112 => 'Refresh API Token',
    113 => 'Change information',
    114 => 'Save',
    115 => 'Delete this Site',
    116 => 'You will not be able to recover this site!',
    117 => 'Your site is safe :)',
    118 => 'Resolution',

    119 => 'Website Response Time',
    120 => 'Uptime',
    121 => 'Uptime Log',
    122 => 'Status',
    123 => 'Response Time',
    124 => 'Time Checked',

    125 => 'Basic Visitor Statistics',
    126 => 'Type',
    127 => 'Bounced',
    128 => 'Recurring visitor',
    129 => 'Visits',
    130 => 'Time on site',

    131 => 'Visitor Details',
    132 => 'Visitor Trail',
    133 => 'Page',
    134 => 'Time on page',
    135 => 'Time',

    136 => 'You can generate Flow reports of your visits to know in detail what they have done on your website, how long they have been and at what point they have abandoned your website.',
    137 => 'Location',
    138 => 'Browser',
    139 => 'Search visitors by specific country',
    140 => 'Search visitors by specific browser',
    141 => 'OS',
    142 => 'Search visitors by specific Operating System',
    143 => 'Search Visitors',

    144 => 'Visitors Found',
    145 => 'Visitor ID',
    146 => 'Last Seen',
    147 => 'Today',
    148 => 'Page Load Time',
    149 => 'Visitors',
    150 => 'Bounce Rate',
    
    151 => 'If you do not know how stablish a random page for your site,',
    152 => 'you can read our little help guide',
    153 => 'to learn how you can do it in a simple way.',
    
    154 => 'Adverts',
    155 => 'UNLIMITED',
    156 => 'Daily Hits',
    157 => 'Days History',
    158 => 'Site/s',
    159 => 'Full Exporting',
    160 => 'No Exporting',
    161 => 'Heatmaps',
    162 => 'API Access',
    163 => 'Form Builder',
    164 => 'Forms',
    165 => 'Submissions',
    
    166 => 'Setup subscription and pay',
    167 => 'now',
    168 => 'Pay',

    170 => 'NEW TIP!',
    171 => 'Read our',
    172 => 'landing page optimization',
    173 => 'article',
    174 => 'Free Tools',
    175 => 'Website & SEO',
    176 => 'DNS Audit Report',
    177 => 'Complete SEO Report',
    178 => 'API Debugging',
    179 => 'Malware Scan',
    180 => 'Url Shortener',
    181 => 'Is up?',
    182 => 'API Debugging',
    183 => 'Submit a Bug',
    184 => 'Server Status',
    185 => 'Roadmap',
    186 => 'How integrate your form in a modal-up',
    187 => 'Increase your conversions with this useful tip that marketers love',
    188 => 'How use your form as Feedback & Bug Report platform',
    189 => 'Every tech start-up knows that this feature is a must',
    190 => 'How can set a randomly pages on your site for your A/B testing processes',
    191 => 'Check our easy tutorial and set random pages on your site with just a little JS sinppet.',
    192 => 'Use your forms as a complete Feedback Polls system',
    193 => 'You do not have to pay for this services to third provider. Our forms is almost magic.',
    194 => 'Learn from your users with our mouse tracking recording system',
    195 => 'Visual learning by recording what your users do on your site. Play de video!',
    196 => 'Better design no just by your intuition, lets heatmaps talks!',
    197 => 'Heat Maps are knowledge, not just information. Better design that works more effectively.',
    198 => 'What works and what not',
    199 => 'A/B testing processes are fundamental to know what\'s work and what not to improve conversion and performanceLas pruebas A/B son fundamentales para saber qué funciona mejor para mejorar tu conversión',
    200 => 'Don\'t need to pay for Uptime Server Monitor',
    201 => 'Kisslytics have a inbuilt complete and easy Server Uptime Monitor',
    202 => '#',
    203 => 'Terms',
    204 => 'Privacy',
    
];